import Head from 'next/head'
import React from 'react'
import Footer from '../../compose/Footer'
import Header from '../../compose/Header'
import Navbar from '../../compose/Navbar'

interface MainProps {
  children: React.ReactNode
  currentPage: string
}

const MainLayout: React.FunctionComponent<MainProps> = ({
  children,
  currentPage,
}) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar currentPage={currentPage} />
      <Header currentPage={currentPage} />
      {children}
      <Footer />
    </div>
  )
}

export default MainLayout
