import type { NextPage } from 'next'
import React from 'react'
import Head from 'next/head'
import Navbar from '../components/compose/Navbar'
import News from '../components/compose/News'
import Pagination from '../components/core/Pagination'
import { products } from '../mocks/news'
import Header from '../components/compose/Header'
import Banner from '../components/compose/Banner'
import Footer from '../components/compose/Footer'

const Home: NextPage = () => {
  return (
    <div className="font-body">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <Header />

      <main>
        <Banner />

        <News products={products} />

        <Pagination />
      </main>

      <Footer />
    </div>
  )
}

export default Home
